version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install -g @angular/cli@17.0.2
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - ng build
artifacts:
  base-directory: 
  files:
    - 'dist/mipools-front-end/browser/*'
