export const CategoryId = {
  football: '1',
  nfl: '2',
  golf: '3',
  racing: '4',
  currentAffairs: '5',
  special: '6',
  rugbyUnion: '7',
  ufc: '8',
  cricket: '9',
  motorSport: '10',
  snooker: '11',
  tennis: '12',
  poker: '13',
  boxing: '14',
  cycling: '15',
  darts: '16',
  baseball: '17',
  rugbyLeague: '18',
  basketball: '19',
  tv: '20',
  chess: '21',
  greyhounds: '22',
  entertainment: '23',
  eSports: '24',
  athletics: '25',
} as const;

export type CategoryId = (typeof CategoryId)[keyof typeof CategoryId];
